const { Resend } = require('resend')

const resend = process.env.RESEND_API_KEY
  ? new Resend(process.env.RESEND_API_KEY)
  : null

async function sendAuditEmail({ to, report }) {
  if (!to) {
    throw new Error('No recipient email address was provided.')
  }

  if (!resend) {
    throw new Error('RESEND_API_KEY is not configured.')
  }

  const text =
    report.emailText ||
    buildFallbackEmailText(report)

  const html =
    buildHtmlEmail(report)

  const from =
    process.env.RESEND_FROM_EMAIL ||
    'Snobo Labs <onboarding@resend.dev>'

  const result =
    await resend.emails.send({
      from,
      to,
      subject:
        `Snobo Labs Audit — ${report.grade} (${report.score}/100)`,
      text,
      html,
    })

  if (result?.error) {
    throw new Error(
      result.error.message ||
      'Resend failed to send the audit email.'
    )
  }

  return {
    id: result?.data?.id || null,
    sent: true,
  }
}

function buildFallbackEmailText(report) {
  const lines = []

  lines.push('SNOBO LABS — WEBSITE AUDIT')
  lines.push('')
  lines.push(`Website: ${report.url}`)
  lines.push(`Score: ${report.score}/100`)
  lines.push(`Grade: ${report.grade}`)
  lines.push('')

  lines.push('PRIORITY FINDINGS')

  const findings = [
    ...(report.findings?.critical || []),
    ...(report.findings?.high || []),
    ...(report.findings?.medium || []),
  ]

  if (!findings.length) {
    lines.push('No major problems were detected.')
  }

  findings.forEach((finding, index) => {
    lines.push(`${index + 1}. ${finding.title}`)

    if (finding.detail) {
      lines.push(`   ${finding.detail}`)
    }

    if (finding.evidence) {
      lines.push(`   Evidence: ${finding.evidence}`)
    }

    lines.push('')
  })

  lines.push('WHAT IS WORKING')

  ;(report.findings?.positive || [])
    .slice(0, 10)
    .forEach((finding, index) => {
      lines.push(
        `${index + 1}. ${finding.title}`
      )
    })

  lines.push('')
  lines.push('Generated by Snobo Labs.')

  return lines.join('\n')
}

function escapeHtml(value) {
  return String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;')
}

function buildHtmlEmail(report) {
  const problems = [
    ...(report.findings?.critical || []),
    ...(report.findings?.high || []),
    ...(report.findings?.medium || []),
  ]

  const positive =
    report.findings?.positive || []

  const problemHtml = problems.length
    ? problems
        .map(
          (item) => `
            <div style="margin-bottom:20px;">
              <strong>${escapeHtml(item.title)}</strong>

              ${
                item.detail
                  ? `<div style="margin-top:6px;">${escapeHtml(item.detail)}</div>`
                  : ''
              }

              ${
                item.evidence
                  ? `<div style="margin-top:6px;font-size:13px;color:#666;">
                      Evidence: ${escapeHtml(item.evidence)}
                    </div>`
                  : ''
              }
            </div>
          `
        )
        .join('')
    : '<p>No major problems were detected.</p>'

  const positiveHtml =
    positive
      .slice(0, 10)
      .map(
        (item) =>
          `<li style="margin-bottom:8px;">${escapeHtml(
            item.title
          )}</li>`
      )
      .join('')

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width,initial-scale=1.0">
  <title>Snobo Labs Website Audit</title>
</head>

<body style="
  margin:0;
  padding:0;
  background:#f5f5f5;
  font-family:Arial,sans-serif;
">

  <div style="
    max-width:720px;
    margin:30px auto;
    background:#ffffff;
    padding:32px;
    border-radius:16px;
  ">

    <h1>Snobo Labs Website Audit</h1>

    <p>
      <strong>Website:</strong>
      ${escapeHtml(report.url)}
    </p>

    <div style="
      padding:20px;
      margin:20px 0;
      background:#f1f1f1;
      border-radius:12px;
    ">
      <div style="
        font-size:32px;
        font-weight:bold;
      ">
        ${escapeHtml(report.score)}/100
      </div>

      <div style="
        font-size:20px;
        margin-top:6px;
      ">
        Grade: ${escapeHtml(report.grade)}
      </div>
    </div>

    <h2>Priority Findings</h2>

    ${problemHtml}

    <h2>What Is Working</h2>

    ${
      positiveHtml
        ? `<ul>${positiveHtml}</ul>`
        : '<p>No positive signals were recorded.</p>'
    }

    <hr style="
      margin:30px 0;
      border:0;
      border-top:1px solid #ddd;
    ">

    <p style="
      font-size:13px;
      color:#666;
    ">
      Snobo Labs reports are based on observable technical
      signals. A missing signal in server-delivered HTML does
      not automatically mean that the website is broken.
      Some websites render content and metadata dynamically.
    </p>

    <p style="
      font-size:13px;
      color:#666;
    ">
      Generated by Snobo Labs.
    </p>

  </div>

</body>
</html>
`
}

module.exports = {
  sendAuditEmail,
  buildFallbackEmailText,
  buildHtmlEmail,
}