function calculateScore(findings) {
  let score = 100

  score -= findings.critical.length * 20
  score -= findings.high.length * 10
  score -= findings.medium.length * 4

  return Math.max(0, Math.min(100, score))
}

function getGrade(score) {
  if (score >= 90) return 'A'
  if (score >= 80) return 'B'
  if (score >= 70) return 'C'
  if (score >= 60) return 'D'
  return 'F'
}

function buildSummary(findings, signals, technical) {
  const totalProblems =
    findings.critical.length +
    findings.high.length +
    findings.medium.length

  const strongestPositive =
    findings.positive
      .slice(0, 3)
      .map((item) => item.title)

  const priorityFixes = [
    ...findings.critical,
    ...findings.high,
    ...findings.medium,
  ]
    .slice(0, 5)
    .map((item) => item.title)

  return {
    totalProblems,

    priorityFixes,

    strongestPositive,

    technical: {
      url: signals.url,
      httpStatus: signals.status,
      responseTimeMs: signals.responseTimeMs,
      robotsTxt:
        technical?.robotsTxt?.reachable || false,
      sitemap:
        technical?.sitemap?.reachable || false,
      https:
        signals.hasSSL,
    },
  }
}

function buildReport({
  signals,
  technical,
  findings,
  pageSpeed = null,
}) {
  const score =
    calculateScore(findings)

  const grade =
    getGrade(score)

  const summary =
    buildSummary(
      findings,
      signals,
      technical
    )

  return {
    version: '2.0',

    generatedAt:
      new Date().toISOString(),

    url:
      signals.url,

    score,

    grade,

    summary,

    signals,

    findings: {
      critical:
        findings.critical,

      high:
        findings.high,

      medium:
        findings.medium,

      positive:
        findings.positive,
    },

    performance:
      pageSpeed || {
        available: false,
        message:
          'A rendered PageSpeed measurement was not available for this audit.',
      },

    disclaimer:
      'Snobo Labs reports are based on observable technical signals. A missing signal in server-delivered HTML does not automatically mean the website is broken. Some websites render content and metadata dynamically.',
  }
}

function formatReportForEmail(report) {
  const lines = []

  lines.push(
    'SNOBO LABS — WEBSITE AUDIT REPORT'
  )

  lines.push('')
  lines.push(
    `Website: ${report.url}`
  )

  lines.push(
    `Score: ${report.score}/100`
  )

  lines.push(
    `Grade: ${report.grade}`
  )

  lines.push('')

  lines.push(
    'SUMMARY'
  )

  lines.push(
    `Problems detected: ${report.summary.totalProblems}`
  )

  if (
    report.summary.priorityFixes.length
  ) {
    lines.push('')
    lines.push(
      'PRIORITY FIXES'
    )

    report.summary.priorityFixes
      .forEach((item, index) => {
        lines.push(
          `${index + 1}. ${item}`
        )
      })
  }

  if (
    report.summary.strongestPositive.length
  ) {
    lines.push('')
    lines.push(
      'WHAT IS WORKING'
    )

    report.summary.strongestPositive
      .forEach((item, index) => {
        lines.push(
          `${index + 1}. ${item}`
        )
      })
  }

  lines.push('')
  lines.push(
    'DETAILED FINDINGS'
  )

  const groups = [
    ['CRITICAL', report.findings.critical],
    ['HIGH', report.findings.high],
    ['MEDIUM', report.findings.medium],
    ['POSITIVE', report.findings.positive],
  ]

  for (const [label, items] of groups) {
    if (!items.length) continue

    lines.push('')
    lines.push(label)

    items.forEach((item, index) => {
      lines.push(
        `${index + 1}. ${item.title}`
      )

      if (item.detail) {
        lines.push(
          `   ${item.detail}`
        )
      }

      if (item.evidence) {
        lines.push(
          `   Evidence: ${item.evidence}`
        )
      }
    })
  }

  lines.push('')
  lines.push(
    'TECHNICAL DETAILS'
  )

  lines.push(
    `HTTP status: ${report.signals.status}`
  )

  lines.push(
    `Response time: ${report.signals.responseTimeMs} ms`
  )

  lines.push(
    `HTTPS: ${report.signals.hasSSL ? 'Yes' : 'No'}`
  )

  lines.push(
    `robots.txt: ${report.summary.technical.robotsTxt ? 'Detected' : 'Not confirmed'}`
  )

  lines.push(
    `Sitemap: ${report.summary.technical.sitemap ? 'Detected' : 'Not confirmed'}`
  )

  lines.push('')
  lines.push(
    'This report is generated by Snobo Labs.'
  )

  return lines.join('\n')
}

module.exports = {
  calculateScore,
  getGrade,
  buildSummary,
  buildReport,
  formatReportForEmail,
}